/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedRouteImport } from './routes/_unauthenticated'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as UnauthenticatedIndexRouteImport } from './routes/_unauthenticated/index'
import { Route as UnauthenticatedRegisterRouteImport } from './routes/_unauthenticated/register'
import { Route as UnauthenticatedLoginRouteImport } from './routes/_unauthenticated/login'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedProjectsNewRouteImport } from './routes/_authenticated/projects/new'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects/$projectId'
import { Route as AuthenticatedProjectsProjectIdIndexRouteImport } from './routes/_authenticated/projects/$projectId/index'
import { Route as AuthenticatedProjectsProjectIdMembersRouteImport } from './routes/_authenticated/projects/$projectId/members'
import { Route as AuthenticatedProjectsProjectIdFilesRouteImport } from './routes/_authenticated/projects/$projectId/files'
import { Route as AuthenticatedProjectsProjectIdPostsPostIdRouteImport } from './routes/_authenticated/projects/$projectId/posts/$postId'

const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedIndexRoute = UnauthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UnauthenticatedRoute,
} as any)
const UnauthenticatedRegisterRoute = UnauthenticatedRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => UnauthenticatedRoute,
} as any)
const UnauthenticatedLoginRoute = UnauthenticatedLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => UnauthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsNewRoute =
  AuthenticatedProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdIndexRoute =
  AuthenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdMembersRoute =
  AuthenticatedProjectsProjectIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdFilesRoute =
  AuthenticatedProjectsProjectIdFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdPostsPostIdRoute =
  AuthenticatedProjectsProjectIdPostsPostIdRouteImport.update({
    id: '/posts/$postId',
    path: '/posts/$postId',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof UnauthenticatedIndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/login': typeof UnauthenticatedLoginRoute
  '/register': typeof UnauthenticatedRegisterRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/projects/$projectId/files': typeof AuthenticatedProjectsProjectIdFilesRoute
  '/projects/$projectId/members': typeof AuthenticatedProjectsProjectIdMembersRoute
  '/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/projects/$projectId/posts/$postId': typeof AuthenticatedProjectsProjectIdPostsPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof UnauthenticatedIndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/login': typeof UnauthenticatedLoginRoute
  '/register': typeof UnauthenticatedRegisterRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/projects/$projectId/files': typeof AuthenticatedProjectsProjectIdFilesRoute
  '/projects/$projectId/members': typeof AuthenticatedProjectsProjectIdMembersRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/projects/$projectId/posts/$postId': typeof AuthenticatedProjectsProjectIdPostsPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_unauthenticated/login': typeof UnauthenticatedLoginRoute
  '/_unauthenticated/register': typeof UnauthenticatedRegisterRoute
  '/_unauthenticated/': typeof UnauthenticatedIndexRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/_authenticated/projects/new': typeof AuthenticatedProjectsNewRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/projects/$projectId/files': typeof AuthenticatedProjectsProjectIdFilesRoute
  '/_authenticated/projects/$projectId/members': typeof AuthenticatedProjectsProjectIdMembersRoute
  '/_authenticated/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/_authenticated/projects/$projectId/posts/$postId': typeof AuthenticatedProjectsProjectIdPostsPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/projects/$projectId'
    | '/projects/new'
    | '/projects/'
    | '/projects/$projectId/files'
    | '/projects/$projectId/members'
    | '/projects/$projectId/'
    | '/projects/$projectId/posts/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/projects/new'
    | '/projects'
    | '/projects/$projectId/files'
    | '/projects/$projectId/members'
    | '/projects/$projectId'
    | '/projects/$projectId/posts/$postId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_unauthenticated'
    | '/_authenticated/dashboard'
    | '/_unauthenticated/login'
    | '/_unauthenticated/register'
    | '/_unauthenticated/'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/projects/new'
    | '/_authenticated/projects/'
    | '/_authenticated/projects/$projectId/files'
    | '/_authenticated/projects/$projectId/members'
    | '/_authenticated/projects/$projectId/'
    | '/_authenticated/projects/$projectId/posts/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  UnauthenticatedRoute: typeof UnauthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/': {
      id: '/_unauthenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof UnauthenticatedIndexRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/register': {
      id: '/_unauthenticated/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof UnauthenticatedRegisterRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/login': {
      id: '/_unauthenticated/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UnauthenticatedLoginRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/new': {
      id: '/_authenticated/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedProjectsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/': {
      id: '/_authenticated/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/members': {
      id: '/_authenticated/projects/$projectId/members'
      path: '/members'
      fullPath: '/projects/$projectId/members'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdMembersRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/files': {
      id: '/_authenticated/projects/$projectId/files'
      path: '/files'
      fullPath: '/projects/$projectId/files'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdFilesRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/posts/$postId': {
      id: '/_authenticated/projects/$projectId/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/projects/$projectId/posts/$postId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPostsPostIdRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
  }
}

interface AuthenticatedProjectsProjectIdRouteChildren {
  AuthenticatedProjectsProjectIdFilesRoute: typeof AuthenticatedProjectsProjectIdFilesRoute
  AuthenticatedProjectsProjectIdMembersRoute: typeof AuthenticatedProjectsProjectIdMembersRoute
  AuthenticatedProjectsProjectIdIndexRoute: typeof AuthenticatedProjectsProjectIdIndexRoute
  AuthenticatedProjectsProjectIdPostsPostIdRoute: typeof AuthenticatedProjectsProjectIdPostsPostIdRoute
}

const AuthenticatedProjectsProjectIdRouteChildren: AuthenticatedProjectsProjectIdRouteChildren =
  {
    AuthenticatedProjectsProjectIdFilesRoute:
      AuthenticatedProjectsProjectIdFilesRoute,
    AuthenticatedProjectsProjectIdMembersRoute:
      AuthenticatedProjectsProjectIdMembersRoute,
    AuthenticatedProjectsProjectIdIndexRoute:
      AuthenticatedProjectsProjectIdIndexRoute,
    AuthenticatedProjectsProjectIdPostsPostIdRoute:
      AuthenticatedProjectsProjectIdPostsPostIdRoute,
  }

const AuthenticatedProjectsProjectIdRouteWithChildren =
  AuthenticatedProjectsProjectIdRoute._addFileChildren(
    AuthenticatedProjectsProjectIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRouteWithChildren
  AuthenticatedProjectsNewRoute: typeof AuthenticatedProjectsNewRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProjectsProjectIdRoute:
    AuthenticatedProjectsProjectIdRouteWithChildren,
  AuthenticatedProjectsNewRoute: AuthenticatedProjectsNewRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface UnauthenticatedRouteChildren {
  UnauthenticatedLoginRoute: typeof UnauthenticatedLoginRoute
  UnauthenticatedRegisterRoute: typeof UnauthenticatedRegisterRoute
  UnauthenticatedIndexRoute: typeof UnauthenticatedIndexRoute
}

const UnauthenticatedRouteChildren: UnauthenticatedRouteChildren = {
  UnauthenticatedLoginRoute: UnauthenticatedLoginRoute,
  UnauthenticatedRegisterRoute: UnauthenticatedRegisterRoute,
  UnauthenticatedIndexRoute: UnauthenticatedIndexRoute,
}

const UnauthenticatedRouteWithChildren = UnauthenticatedRoute._addFileChildren(
  UnauthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  UnauthenticatedRoute: UnauthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
