/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/api/health": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Health Check
		 * @description Check API and database connectivity
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description API is healthy */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["HealthyResponse"];
					};
				};
				/** @description API is unhealthy */
				503: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["UnhealthyResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		HealthyResponse: {
			/** @enum {string} */
			status: "healthy";
			timestamp: string;
			uptime: number;
		};
		UnhealthyResponse: {
			/** @enum {string} */
			status: "unhealthy";
			timestamp: string;
			error: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
