/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/api/files/{fileId}/download": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Download a file */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					fileId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description File content */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description Not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/health": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Health Check
		 * @description Check API and database connectivity
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description API is healthy */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["HealthyResponse"];
					};
				};
				/** @description API is unhealthy */
				503: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["UnhealthyResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/notifications": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List notifications */
		get: {
			parameters: {
				query?: {
					page?: number;
					limit?: number;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description List of notifications */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["NotificationList"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/notifications/unread-count": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get unread notification count */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Unread count */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["UnreadCount"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/notifications/{notificationId}/read": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** Mark a notification as read */
		patch: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					notificationId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Marked as read */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description Not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		trace?: never;
	};
	"/api/notifications/mark-all-read": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Mark all notifications as read */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description All marked as read */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/projects": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List projects
		 * @description Lists projects the user owns or has been shared with
		 */
		get: {
			parameters: {
				query?: {
					page?: number;
					limit?: number;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description List of projects */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ProjectList"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		/** Create a project */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": components["schemas"]["CreateProjectBody"];
				};
			};
			responses: {
				/** @description Project created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Project"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/projects/{projectId}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get a project */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					projectId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Project details */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Project"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description Not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		/**
		 * Delete a project
		 * @description Only the project owner can delete a project
		 */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					projectId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Project deleted */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description Not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		options?: never;
		head?: never;
		/**
		 * Update a project
		 * @description Only the project owner can update a project
		 */
		patch: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					projectId: string;
				};
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": components["schemas"]["UpdateProjectBody"];
				};
			};
			responses: {
				/** @description Project updated */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Project"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description Not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		trace?: never;
	};
	"/api/projects/{projectId}/members": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List project members */
		get: {
			parameters: {
				query?: {
					page?: number;
					limit?: number;
				};
				header?: never;
				path: {
					projectId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description List of members */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ProjectMemberList"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description Not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		/**
		 * Share a project with a user
		 * @description Only the project owner can share a project
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					projectId: string;
				};
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": components["schemas"]["ShareProjectBody"];
				};
			};
			responses: {
				/** @description Member added */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ProjectMember"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description User or project not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description User is already a member */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/projects/{projectId}/members/{memberId}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/**
		 * Remove a member from a project
		 * @description Only the project owner can remove members
		 */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					projectId: string;
					memberId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Member removed */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description Not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/projects/{projectId}/posts": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List posts in a project */
		get: {
			parameters: {
				query?: {
					page?: number;
					limit?: number;
				};
				header?: never;
				path: {
					projectId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description List of posts */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["PostList"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description Project not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		/** Create a post in a project */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					projectId: string;
				};
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": components["schemas"]["CreatePostBody"];
				};
			};
			responses: {
				/** @description Post created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Post"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description Project not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/projects/{projectId}/posts/{postId}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get a post with its comments */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					projectId: string;
					postId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Post with comments */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["PostWithComments"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description Not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		/**
		 * Delete a post
		 * @description Post author or project owner can delete
		 */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					projectId: string;
					postId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Post deleted */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description Not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/projects/{projectId}/posts/{postId}/comments": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List comments on a post */
		get: {
			parameters: {
				query?: {
					page?: number;
					limit?: number;
				};
				header?: never;
				path: {
					projectId: string;
					postId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description List of comments */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["CommentList"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description Project or post not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		/** Add a comment to a post */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					projectId: string;
					postId: string;
				};
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": components["schemas"]["CreateCommentBody"];
				};
			};
			responses: {
				/** @description Comment created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["Comment"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description Project or post not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/projects/{projectId}/posts/{postId}/comments/{commentId}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/**
		 * Delete a comment
		 * @description Comment author or project owner can delete
		 */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					projectId: string;
					postId: string;
					commentId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Comment deleted */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description Not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/projects/{projectId}/files": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List files in a project */
		get: {
			parameters: {
				query?: {
					page?: number;
					limit?: number;
				};
				header?: never;
				path: {
					projectId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description List of files */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["FileList"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description Project not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		/**
		 * Upload a file to a project
		 * @description Accepts image files up to 10MB (JPEG, PNG, GIF, WebP, SVG)
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					projectId: string;
				};
				cookie?: never;
			};
			requestBody?: {
				content: {
					"multipart/form-data": {
						/** Format: binary */
						file: string;
					};
				};
			};
			responses: {
				/** @description File uploaded */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ProjectFile"];
					};
				};
				/** @description Invalid file type or size */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description Project not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/projects/{projectId}/files/{fileId}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/**
		 * Delete a file
		 * @description Uploader or project owner can delete
		 */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					projectId: string;
					fileId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description File deleted */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description Not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/test/sentry-error": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Test Sentry Error Capture
		 * @description Throws an error to verify Sentry is capturing backend exceptions
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Throws an error to test Sentry integration */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/test/admin-only": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Test Admin Access
		 * @description Endpoint that requires admin role to access
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Success - user has admin role */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": {
							message: string;
							user: {
								id: string;
								email: string;
								role: string;
							};
						};
					};
				};
				/** @description Unauthorized - no valid session */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
				/** @description Forbidden - user is not an admin */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		ErrorResponse: {
			error: {
				code: string;
				message: string;
				details?: unknown;
			};
		};
		HealthyResponse: {
			/** @enum {string} */
			status: "healthy";
			timestamp: string;
			uptime: number;
		};
		UnhealthyResponse: {
			/** @enum {string} */
			status: "unhealthy";
			timestamp: string;
			error: string;
		};
		NotificationList: {
			data: components["schemas"]["Notification"][];
			pagination: components["schemas"]["PaginationMeta"];
		};
		Notification: {
			id: string;
			type: string;
			message: string;
			read: boolean;
			projectId: string | null;
			postId: string | null;
			createdAt: string;
			actorName: string;
		};
		PaginationMeta: {
			page: number;
			limit: number;
			total: number;
			totalPages: number;
		};
		UnreadCount: {
			count: number;
		};
		Project: {
			id: string;
			name: string;
			description: string | null;
			ownerId: string;
			createdAt: string;
			updatedAt: string;
			/** @enum {string} */
			role: "owner" | "contributor";
		};
		CreateProjectBody: {
			name: string;
			description?: string;
		};
		ProjectList: {
			data: components["schemas"]["Project"][];
			pagination: components["schemas"]["PaginationMeta"];
		};
		UpdateProjectBody: {
			name?: string;
			description?: string;
		};
		ProjectMember: {
			id: string;
			projectId: string;
			userId: string;
			role: string;
			createdAt: string;
			userName: string;
			userEmail: string;
		};
		ShareProjectBody: {
			/** Format: email */
			email: string;
		};
		ProjectMemberList: {
			data: components["schemas"]["ProjectMember"][];
			pagination: components["schemas"]["PaginationMeta"];
		};
		Post: {
			id: string;
			projectId: string;
			authorId: string;
			title: string;
			content: string;
			createdAt: string;
			updatedAt: string;
			authorName: string;
		};
		CreatePostBody: {
			title: string;
			content: string;
		};
		PostList: {
			data: components["schemas"]["PostDetail"][];
			pagination: components["schemas"]["PaginationMeta"];
		};
		PostDetail: components["schemas"]["Post"] & {
			commentCount: number;
		};
		PostWithComments: components["schemas"]["Post"] & {
			comments: components["schemas"]["CommentInPost"][];
		};
		CommentInPost: {
			id: string;
			postId: string;
			authorId: string;
			content: string;
			createdAt: string;
			authorName: string;
		};
		Comment: {
			id: string;
			postId: string;
			authorId: string;
			content: string;
			createdAt: string;
			authorName: string;
		};
		CreateCommentBody: {
			content: string;
		};
		CommentList: {
			data: components["schemas"]["Comment"][];
			pagination: components["schemas"]["PaginationMeta"];
		};
		ProjectFile: {
			id: string;
			projectId: string;
			uploaderId: string;
			filename: string;
			mimeType: string;
			sizeBytes: number;
			createdAt: string;
			uploaderName: string;
		};
		FileList: {
			data: components["schemas"]["ProjectFile"][];
			pagination: components["schemas"]["PaginationMeta"];
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
